# Site settings
author: Serafina Gomes
title: Serafina's Data Science Blog
header-img: img/home-bg.png
email: jpgomes271@gmail.com
copyright_name: Serafina Gomes
description: > # this means to ignore newlines until "baseurl:"
  Making sense of it all
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SouloftheSword271

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
